const INVENTORY_TRANSACTION_TYPE = {

    STOCK_IN:"STOCK_IN",

    STOCK_OUT:"STOCK_OUT",

    TRANSFER:"TRANSFER",

    DAMAGE:"DAMAGE",

    ADJUSTMENT:"ADJUSTMENT"

};

module.exports = INVENTORY_TRANSACTION_TYPE;