const ROLES = {
  OWNER: "OWNER",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  SITE_ENGINEER: "SITE_ENGINEER",
  STORE_MANAGER: "STORE_MANAGER",
  ACCOUNTANT: "ACCOUNTANT",
  WORKER: "WORKER",
  CLIENT: "CLIENT",
};

module.exports = ROLES;